add custom deserializer to allow for null feature descriptions
Unleash/unleash-client-rust pull request #66
Opened 2023-09-24 23:25 UTC by masonj5n

## About the changes

I was trying out Unleashed for the first time (product is awesome!) but noticed features would never become enabled in the Rust client. I noticed if I only had features with descriptions things _did_ work, and tracked it down to the poller failing to parse the features from json. Not relevant to the Rust sdk but it does seem like if you create a new feature and don't give a description, the field is `null` in the json response, but if you create it with a description but then erase the description and save it, it returns `""` instead of `null`.

In any case, the `description` field on a `feature` can be `null` - when it is `null` it fails to parse since it's represented by a `String` in the Rust representation.

The obvious way to fix this would be just changing `description: String` to `description: Option<String>`, but it does seem like it was intentional since there are other optional fields and it has a `#[serde(default)]` attribute. Maybe someone has some more context on that?

The default serde attribute isn't enough in this case because it doesn't apply when the field is present, but set to null, it only applies if the field isn't given at all.

Assuming it was intentional to not make the description optional, this parser should turn an incoming `description: null` into `description: ""`.

I added a test that fails before this change but passes afterward.

### Important files

## Discussion points

If it wasn't intentional to make the description optional we can go that route instead and just make it optional. I think there's some more work to do there since there is other code that assumes it'll always be present, but happy to do that if that's the route we want to go.

2023-09-27 07:43 UTC, thomasheartman commented
This looks and sounds (and smells?) like a sensible change to me! I'll have a look later on today or this week 😄 Thanks for your contribution 🙏🏼

2023-09-27 08:34 UTC, thomasheartman requested changes
So I had a look and I can confirm that I'm seeing the same behavior as you. If a flag's description is `null`, the SDK fails to parse the response. It seems strange that this hasn't been caught before, though, so I'm wondering if it's a recent issue 🤔 

I think you're right that just making the description an `Option<String>` or even removing that field entirely (it's never used by the SDK at all) would be an easier way to go here, so I'm going to suggest that we do that instead. That saves us updating the imports and adding the custom deserialization. Should be enough to just change the type.

So my request is that you remove the description property of the `Feature` struct entirely. That way, the only changes should be the deletion of line 26 and the new tests.

Now this is technically a breaking change (but so would changing the type be), but there's no sense in keeping this data that I can see. Plus, we're still pre-1.0, so we can bump this in a minor update.

Thanks again for bringing this issue to our attention and for providing a fix 🙌🏼  We'll get this merged as soon as the property is gone 😄

2023-09-28 05:01 UTC, masonj5n commented
Hey, thanks for the quick response!

Glad to hear we don't need to go that custom deserializer route! I updated the PR to make the field optional instead of removing it completely - the reasoning is just that if the `strict` feature is enabled, the parsing will _always_ fail since `description` is _always_ present in the response from the api, iiuc.

If we want to remove the field completely it seems like it might be best to also remove the `strict` feature from the crate, since if we delete the field that feature will always break the parsing?

If the change to optional works I think this should be g2g, happy to remove the field entirely and remove the `strict` feature (or just remove `#[cfg_attr(feature = "strict", serde(deny_unknown_fields))]` from the feature struct) if that's better too.

2023-09-28 07:17 UTC, thomasheartman approved these changes
@masonj5n Yeah, I think you're right on the money here. I hadn't considered the `strict` mode, so that's a very good catch. I think this is good to go now 😄  Thanks again for the contribution and for how quickly you made the changes 🙌🏼

2023-09-28 07:19 UTC, thomasheartman commented
@masonj5n Ah, sorry; looks like clippy found a couple places where you'd forgotten to wrap the name in an Option in `benches/is_enabled.rs`. Would you mind going to clean up?

2023-09-28 19:22 UTC, masonj5n commented
Whoops, sorry about that! Should be good now

2023-09-29 08:03 UTC, thomasheartman commented
@masonj5n Thanks a lot for your contribution! 🙏🏼  I took the liberty of rebasing your changes into a single commit and adding a little more context in the commit message. I'll go ahead and merge this once the CI jobs have run. Will sort out a release shortly too 😄

2023-09-29 08:08 UTC, merged